name: HACS validation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  hacs:
    name: Run HACS validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: HACS validation
        uses: hacs/action@main
