name: HACS validation

on:
  push:
  pull_request:

jobs:
  hacs:
    name: Run HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          repository: nocturno66/MicroPIC-Energy-Meter-comp
